### PR TITLE
Bulgarian support

### PR DESCRIPTION
**Pull request by hristo-vrigazov**
Added support for Bulgarian languages, including tests.

### CODE REVIEW

**Comment by hristo-vrigazov** [comment]
@waqasshabbir Yes, sorry. I used the Hebrew pull request #241 as a reference, but missed the complete dates. You are asking for tests in `test_date.py`, `test_date_parser.py`, and `test_freshness_date_parser.py`, right? I will do it as soon as I have some free time.

**Comment by waqasshabbir** [comment]
@hristo-vrigazov oh if you could add more tests to hebrew that we missed that will be great too. If you need help with this, just let me know. I'm planning a release this weekend and would like to include your contribution. Thanks!

**Comment by hristo-vrigazov** [comment]
I don't know Hebrew, I was just looking at what files the guy has changed, and added tests in the same files. So, exactly where should I add more tests? `test_date.py`, `test_date_parser.py`, and `test_freshness_date_parser.py`, do you mean these? Today or tomorrow I will add them if I can

**Comment by hristo-vrigazov** [comment]
@waqasshabbir  Added tests, should be ready now. Note that another language was added in between, and you should include both versions (Bulgarian and Bangla) when merging.

**Comment by hristo-vrigazov** [comment]
You should add commas where the branches conflict, this breaks the syntax :( sorry

**Comment by waqasshabbir** [comment]
thanks for your help! fixed that and merged the PR already.

**Pull request merged**
