### PR TITLE
Extending YAML Files

### PR DESCRIPTION
**Pull request by harsh9200**
Transferring Data from JSON Files to YAML Files. 

Context: https://github.com/scrapinghub/dateparser/pull/638#issuecomment-620696368

### CODE REVIEW

**Comment by harsh9200** [comment]
Please Review @Gallaecio

**Comment by noviluni** [comment]
Is this PR finished? In that case, could you remove the "[WIP]" from the title? @harsh9200

**Comment by harsh9200** [comment]
> Is this PR finished? 
No, I will add more data so that my other PR's can also be merged. I will inform you when I am done.

@noviluni

**Comment by harsh9200** [comment]
This PR is ready now.

@noviluni

**Pull request closed without merging**
