### PR TITLE
Added russian "tomorrow"

### PR DESCRIPTION
**Pull request by Sorseg**
Ran tests locally

### CODE REVIEW

**Comment by Yegorov** [comment]
Maybe need add to section "in" - спустя. (For examaple: "спустя год"). And add to "simplifications" - сейчас, послезавтра.

**Comment by Sorseg** [comment]
@Yegorov good call, will get on it on weekend.

**Comment by Sorseg** [comment]
@Yegorov totally forgot about this one.

**Comment by waqasshabbir** [comment]
Thanks @Sorseg, @Yegorov. Merging already.

**Pull request merged**
