### PR TITLE
Update th.yaml

### PR DESCRIPTION
**Pull request by andjelx**
Added ที่ (thi) at the end for days of week

### CODE REVIEW

**Comment by tastepwalle** [comment]
Seems this PR passed..we need this update can it be merged? :)

Awesome library btw

**Comment by asadurski** [comment]
Can you please add some tests for those weekdays to make it quicker? (Or suggest date strings and datetime result for those).

**Comment by andjelx** [comment]
I will add tests

**Comment by andjelx** [comment]
I have added few tests

**Comment by andjelx** [comment]
Hello @asadurski do you have any feedback on my PR?
Travis failed only on one job and seems it's an internal issue not related to PR itself.

**Comment by asadurski** [comment]
You're right, the problem was with the setup of tests in Travis.
Thank you for contribution. Apologies for long wait time.

**Comment by tastepwalle** [comment]
@asadurski thanks for merging, much appreciated.

By chance do you know when the PyPI package will be updated? Thanks, P

**Pull request merged**
