### PR TITLE
[Russian] added month abbreviations

### PR DESCRIPTION
**Pull request by asadurski**
Three-letter month abbreviations for Russian, encountered on some websites.

### CODE REVIEW

**Comment by waqasshabbir** [comment]
As @Allactaga can provide more qualified insight here. I'd just like to refer to this source with abbreviated month names in different languages.
http://library.princeton.edu/departments/tsd/katmandu/reference/months.html
https://lts.library.cornell.edu/lts/pp/spp/mosabbr#french

**Comment by asadurski** [comment]
These were meant as a solution for a particular site, but why not, I can make a run for applying the abbreviations for other languages from those sources. I'd do it in another PR though.

**Comment by Allactaga** [comment]
Let's add first form for all months: Январь, Февраль, Март, Апрель, Май, Июнь, Июль, Август, Сентябрь, Октябрь, Ноябрь, Декабрь.

**Comment by Allactaga** [comment]
Also, may be couple of test strings from the particular site?

**Pull request merged**
