### PR TITLE
Fix issue #571  : Add 24hr format support

### PR DESCRIPTION
**Pull request by Avilad0**
Fix issue #571

adds 24hr format support
adds decimal format support i.e. single digit specifications in time

### CODE REVIEW

**Comment by Gallaecio** [comment]
Could you add tests covering the scenarios that are now fixed? It should be easy to extend existing tests to cover new input strings and output dates.

**Comment by Avilad0** [comment]
please refer #654 for the pull request related to the test cases

**Comment by Gallaecio** [comment]
https://github.com/scrapinghub/dateparser/pull/654 seems to supersede this pull request. Should we close this?

**Comment by Avilad0** [comment]
Yes.. we can close this 👍

**Pull request closed without merging**
