### PR TITLE
[MRG+1] Check prefer_dates_from when parsing strings like "3 days"

### PR DESCRIPTION
**Pull request by Watchful1**
If prefer_dates_from is set to future, default to future for cases like "3 days"

### CODE REVIEW

**Comment by Gallaecio** [comment]
I’ve added `[WIP]` to the title of your pull request, please remove it or let us know when your code is ready for a review.

**Comment by Watchful1** [comment]
I haven't made any changes since last August, it's been ready to merge since then. The latest two commits were just merging master in.

**Comment by Gallaecio** [comment]
Sorry, I did not noticed the dates. Could you include an automated test covering your changes?

**Comment by Watchful1** [comment]
Added a test.

I somewhat think that prefer future should be the default, instead of prefer past like it is currently. I don't think someone would say "3 days" and mean three days in the past.

**Comment by Watchful1** [comment]
I'm re-submitting this pull request as #530 which is identical, but is from a separate branch so I keep making changes without polluting this pull request.

**Pull request closed without merging**
