### PR TITLE
Remove utf declaration strings.

### PR DESCRIPTION
**Pull request by kishan3**
For #727

### CODE REVIEW

**Comment by noviluni** [comment]
Hi @kishan3! thank you for addressing this.

First of all, I think it will be better if, instead of changing the utf line with a blank line, you directly remove them, in that way we won't be having an empty line at the beginning of each file. You did it in some files.

Apart from that, the pipelines are failing because of two reasons:

1. flake8

You can check them here: https://travis-ci.org/github/scrapinghub/dateparser/jobs/713286313

* `dateparser/data/numeral_translation_data/__init__.py:1:1: W391 blank line at end of file`
* `dateparser/data/date_translation_data/__init__.py:1:1: W391 blank line at end of file`

It seems that you added extra lines in those `__init__.py` files.

2. `The content of the file "../dateparser/data/date_translation_data/*.py" doesn't match the content of the generated file.`

This is a test that checks that the files in `dateparser/data/date_translation_data/` are not edited directly. The `write_complete_data.py` script adds the encoding comment and when it compares the generated file with the file it's different, so you have two options:

a) Don't change neither the script nor the files in `dateparser/data/date_translation_data/`. We can open a new PR for handling the script changes.
b) Undo the changes you have made in the files in `dateparser/data/date_translation_data/`, update the script avoiding it from adding the utf-8 comment in the generated files, and, after that, run `write_complete_data.py`. 

Let me know what you choose :)

**Comment by kishan3** [comment]
Hi @noviluni Thanks for the feedback. 
- For files inside `dateparse/data/..` I created another PR with what you mentioned in option "b" #761

**Comment by noviluni** [comment]
Hi @kishan3! Let me know when it's ready for review by removing the `[WIP]` :)

**Comment by kishan3** [comment]
Oops forgot to remove it @noviluni. Done now!

**Comment by Gallaecio** [comment]
“This branch cannot be rebased due to conflicts”

**Comment by noviluni** [comment]
Hi @kishan3, could you rebase/fix the conflicting files? :)

**Comment by kishan3** [comment]
Done @noviluni !

**Pull request merged**
