### PR TITLE
Introducing regex module

### PR DESCRIPTION
**Pull request by asadurski**
Introduction of `regex` module (used instead of standard `re`) will allow for more flexible approach to regular expressions.

### CODE REVIEW

**Comment by sardok** [comment]
It would be better to put it in ```requirements.txt``` as well.

**Comment by asadurski** [comment]
Yup, it's already there: https://github.com/scrapinghub/dateparser/commit/560756f044ace493a85b387fa04c4d0eefdb56db#diff-b4ef698db8ca845e5845c4618278f29aR3

**Comment by sardok** [comment]
Sorry, artur, missed that.

**Comment by waqasshabbir** [comment]
This looks good. Can we raise a warning when `re` module is used? Urging to use `regex` instead.

**Pull request merged**
