### PR TITLE
Added numbers upto twelve (fix for #291)

### PR DESCRIPTION
**Pull request by atultherajput**
I had added numbers upto twelve in languagefiles/en.yaml 
This is a fix for #291 
Please review this patch @waqasshabbir and @asadurski

### CODE REVIEW

**Comment by atultherajput** [comment]
Thanks @asadurski but Why this build is failed?

**Comment by redapple** [comment]
Travis is reporting 2 failed tests (see for example [the Python 2.7 build](https://travis-ci.org/scrapinghub/dateparser/jobs/215823376)):
```
======================================================================
FAIL: test_relative_past_dates_27_in_eight_months (tests.test_freshness_date_parser.TestFreshnessDateDataParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/scrapinghub/dateparser/.tox/py27/lib/python2.7/site-packages/nose_parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/travis/build/scrapinghub/dateparser/tests/test_freshness_date_parser.py", line 333, in test_relative_past_dates
    self.then_date_obj_is_exactly_this_time_ago(ago)
  File "/home/travis/build/scrapinghub/dateparser/tests/test_freshness_date_parser.py", line 910, in then_date_obj_is_exactly_this_time_ago
    self.assertEqual(self.now - relativedelta(**ago), self.result['date_obj'])
AssertionError: datetime.datetime(2014, 1, 1, 10, 30) != datetime.datetime(2015, 5, 1, 10, 30)
======================================================================
FAIL: test_relative_past_dates_29_in_5_years (tests.test_freshness_date_parser.TestFreshnessDateDataParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/scrapinghub/dateparser/.tox/py27/lib/python2.7/site-packages/nose_parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/travis/build/scrapinghub/dateparser/tests/test_freshness_date_parser.py", line 333, in test_relative_past_dates
    self.then_date_obj_is_exactly_this_time_ago(ago)
  File "/home/travis/build/scrapinghub/dateparser/tests/test_freshness_date_parser.py", line 910, in then_date_obj_is_exactly_this_time_ago
    self.assertEqual(self.now - relativedelta(**ago), self.result['date_obj'])
AssertionError: datetime.datetime(2009, 9, 1, 10, 30) != datetime.datetime(2019, 9, 1, 10, 30)
```

**Comment by atultherajput** [comment]
Thanks for input @redapple

**Comment by waqasshabbir** [comment]
@atultherajput adding simplifications mapping like that isn't the best solution here. Counting doesn't end at twelve. Can you think of some other generic solution?

**Comment by asadurski** [comment]
Since we still don't have any better solution for numerals than simplifications, I believe this is good enough solution in the meantime. I just updated it to fit new data scheme.
Thank you for your contribution, @atultherajput!

**Pull request merged**
