### PR TITLE
Remove encoding from ordering languages script

### PR DESCRIPTION
**Pull request by kishan3**
#727

### CODE REVIEW

**Comment by Gallaecio** [comment]
Shouldn’t we also remove https://github.com/scrapinghub/dateparser/blob/master/dateparser/data/languages_info.py#L1 as part of this request, though?

**Comment by kishan3** [comment]
Right @Gallaecio When I tried to run the script it gave me the following error. Am I running it wrong?
```
python dateparser_scripts/order_languages.py

Traceback (most recent call last):
  File "dateparser_scripts/order_languages.py", line 33, in <module>
    language_locale_dict = _get_language_locale_dict()
  File "dateparser_scripts/order_languages.py", line 17, in _get_language_locale_dict
    available_locale_names = os.listdir(cldr_dates_full_dir)
OSError: [Errno 2] No such file or directory: '../raw_data/cldr_dates_full/main/'
```

**Comment by noviluni** [comment]
> Right @Gallaecio When I tried to run the script it gave me the following error. Am I running it wrong?

These scripts are not normally used and should be checked (some parts as the path handlings are really broken), but the last time I used this script, it worked. 

If this error is happening, what's probably happening is that you have an empty/wrong `raw_data` directory. Please, check if you have that directory in the project or even outside (at the same level as the project) and delete it. It should work after that.

However, I don't recommend you to run this script, as it updates the order of the languages (downloading the last version of the repo from Github) and we don't want this to happen until we address this: https://github.com/scrapinghub/dateparser/issues/714, so you can remove that line directly in the `languages_info.py` file.

Let me know if you have any doubt. :slightly_smiling_face: 

@kishan3

**Comment by kishan3** [comment]
Thanks @noviluni for detailed explanation :rocket: I have updated the manually.

**Pull request merged**
