### PR TITLE
added NumberParser(InternationalSystemEnglish)

### PR DESCRIPTION
**Pull request by XtremeGood**
Number Parser for solving issue https://github.com/scrapinghub/dateparser/issues/46 and Gsoc 2020.

### CODE REVIEW

**Comment by XtremeGood** [comment]
@kishan3 and @marcosmadr I want to participate in GSoC 2020 under the project "Number Parser" and similar ones. As discussed https://github.com/scrapinghub/dateparser/issues/46 I do not think a machine learning model would outperform parsing if done in a good way. Improving code style and testing are still left but wouldn't be too difficult to follow. Please explain what more do you expect from a person doing this project. I know deep learning and RNN/(or CNN) architectures and can use them if required for this project. Also I have good knowledge of data Structures and Algorithms like Knuth Morris Pratt, Trie(Understanding and implementation of Kasai's algorithm), trees/graph  and traversals. 
Thanks,
XtremeGood

**Comment by XtremeGood** [comment]
Hi I though again about this but I dont think if you are working on so many languages(of which I might know only 1 of them) it wouldn't be possible to create it for all different languages(since you need to understand each one of them). Therefore if I have generated the code above then I can use google translate to generate data for all numbers in various languages which I can feed to the model to get the numeric as output. Please reply @kishan3  and @marcosmadr

**Comment by Gallaecio** [comment]
> Please explain what more do you expect from a person doing this project.

I believe the main goal would be to implement such a parser within Dateparser in a way that it can be made to work with different languages.

While I don’t think the project needs to implement that language support, I believe it should implement all the pieces needed for it, so that experts in a language can create a data file, similar to those YAML files we use at the moment, to add natural number parsing support for a language.

And, of course, for Dateparser supporting cardinal numbers would not be enough. Days of the month are usually expressed as ordinal numbers in English.

**Comment by XtremeGood** [comment]
In that case a machine learning model would be a must. Since I only know English. My current idea is to use the cardinal/English model and google translate to generate data for months, date, year in language and train the model on that data to produce the numberic/target value. Will submit a proposal by the end of the day. Sent from Mail for Windows 10 From: Adrián ChavesSent: 27 March 2020 02:31To: scrapinghub/dateparserCc: Vishesh Mangla; AuthorSubject: Re: [scrapinghub/dateparser] added NumberParser(InternationalSystemEnglish) (#647) Please explain what more do you expect from a person doing this project.I believe the main goal would be to implement such a parser within Dateparser in a way that it can be made to work with different languages.While I don’t think the project needs to implement that language support, I believe it should implement all the pieces needed for it, so that experts in a language can create a data file, similar to those YAML files we use at the moment, to add natural number parsing support for a language.And, of course, for Dateparser supporting cardinal numbers would not be enough. Days of the month are usually expressed as ordinal numbers in English.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by asadurski** [comment]
Psst! You already got most of the translations you need under https://github.com/scrapinghub/dateparser/tree/master/dateparser_data/cldr_language_data/numeral_translation_data.

**Comment by XtremeGood** [comment]
That makes it easier. But still as we discussed in the chat on GitHub I don’t think there’s a way to create all that parsing without the knowledge of all those languages or machine learning. I have studied French for 6 years that’s why I m saying this. Consider the following:seventeenth april(in English) dix-sept avril(in french). The order of the words get swapped in french. Now considering the number of languages in the world it is impossible to recognise patterns and parse the string to its numerical form that too for day, month etc. Best we can do is only to use a machine learning/deep learning model and leave it to train continuously. By the way “spacy” already has a “label data” which recognises dates, organisation etc in a sentence. It can be used to collect data from large corpus. I will try adding it to the proposal. Please tell whether I should add machine learning or not since I do not have any other method in my mind to achieve this.    Sent from Mail for Windows 10 From: Artur SadurskiSent: 27 March 2020 16:00To: scrapinghub/dateparserCc: Vishesh Mangla; AuthorSubject: Re: [scrapinghub/dateparser] added NumberParser(InternationalSystemEnglish) (#647) Psst! You already got most of the translations you need under https://github.com/scrapinghub/dateparser/tree/master/dateparser_data/cldr_language_data/numeral_translation_data.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by XtremeGood** [comment]
> 
> 
> > Please explain what more do you expect from a person doing this project.
> 
> I believe the main goal would be to implement such a parser within Dateparser in a way that it can be made to work with different languages.
> 
> While I don’t think the project needs to implement that language support, I believe it should implement all the pieces needed for it, so that experts in a language can create a data file, similar to those YAML files we use at the moment, to add natural number parsing support for a language.
> 
> And, of course, for Dateparser supporting cardinal numbers would not be enough. Days of the month are usually expressed as ordinal numbers in English.

Well ordinal number's just have "th" or "nd" at the end. It's just the suffix root that is changed.[Cardinal and ordinal Numbers](https://www.mathsisfun.com/numbers/cardinal-ordinal-chart.html).That's is pretty simple to do. One can just create new keys in the dictionary in the code dictionary["first"] = 1 and so on. Main thing is algorithm which I think works for atleast pricing. Now if I assume all languages to follow similar structure like English then I can think of creating multiple keys for a single target. Is there any chat room to communicate?

**Comment by Gallaecio** [comment]
If you can figure out a system that can work for both English and French, and similar languages provided data from ICU or provided by users in YML format. I think that is a good approach, and I would be satisfied if a GSoC project yields at least that.

Once such a system is in place, people from the community with knowledge of other languages can give feedback about the issues that it presents for other languages, and we can improve the system as needed with feedback. Even if only mentors give feedback, that should be 2-3 more languages which you could work on supporting.

**Comment by XtremeGood** [comment]
Hi, I would require a little bit of more info regarding what things are to be convered. Can we have a chat on gitter or ircnode?

**Comment by Gallaecio** [comment]
I would prefer to discuss them here unless there is a good reason not to. That said, given how close we are to the deadline, I’ll try and be available at [Freenode’s `#dateparser` room](https://webchat.freenode.net/#dateparser).

**Comment by XtremeGood** [comment]
Hi, I have messaged on the ircnode chat. Please reply so that I can sent the proposal asap. Maybe there may be a few hours left to ask for amendments too.

**Comment by arnavkapoor** [comment]
Hi, @Gallaecio @asadurski  @kishan3  @marcosmadr  I am interested in this project and would like to work towards it. Please find attached my GSoC proposal. Would appreciate if you could go through it and provide feedback. Sorry for the short notice.
https://docs.google.com/document/d/17ElRkrvvMBqHXOhFd4_VXc0gG69kpu3GPrAffYFTf4g/edit#

**Comment by XtremeGood** [comment]
@Gallaecio What kind of text do you scrape with dateparser? Is it like dates written in html tables or dates in between large paragraphs of text?

**Comment by harsh9200** [comment]
@XtremeGood 

Mainly `dateparser.parse()` is used to parse dates in a particular format but it can be also used for paragraphs. whereas function `dateparser.search.search_dates()` is used to find dates in a paragraph. The various available format you can find in `dateparser.parse.py`.

**Comment by XtremeGood** [comment]
ok thanks for the info @harsh9200 .

**Comment by XtremeGood** [comment]
Hi @Gallaecio , Why am I not able to find find ScrappingHub in GSoC's organisations?
image

**Comment by XtremeGood** [comment]
I have shared the draft through the Python org under Scrapy. Please check.

**Comment by Gallaecio** [comment]
@XtremeGood What are your current plans on addressing input of unknown language? Rely on some kind of language detection? Apply all word-to-number changes regardless of the input language?

**Comment by XtremeGood** [comment]
Well if you have a text split it into words and compare how many words of the text matches with your each language dictionary. The language dictionary with the most words common won. No other approach except for machine learning in my mind.

**Comment by Gallaecio** [comment]
Sounds like language detection, then :slightly_smiling_face:

**Comment by XtremeGood** [comment]
If you see this is called bag of words as the approach suggests and is umm.. machine learning. I also have a better approach in mind which is called Light Gradient Boosting Machines which are very fast and people are winning competitions on due to the speed of LGBM Kaggle the hub for machine learning. During the community bonding I will to make it. We can compare if it is fast enough.
https://www.kaggle.com/fabiendaniel/detecting-malwares-with-lgbm

**Comment by arnavkapoor** [comment]
Hi @XtremeGood , I have looked for possible ML-based solution to this problem. Do you have any good literature or better similar projects to back up this approach, especially considering the speed and the multitude of languages to accommodate ?. Most of the similar projects that I have come across stick to rule-based approaches only.

**Comment by noviluni** [comment]
I will close this PR as we are handling this with another approach: https://github.com/scrapinghub/dateparser/pull/711

@XtremeGood Thank you for your efforts here, really appreciated :muscle:

**Pull request closed without merging**
