### PR TITLE
Added Fix for "x days from now"

### LINKED ISSUE #502: "x days from now" relative no longer functions as of 0.7
This is not resolved in 0.7.1 either.

0.6.0 shows expected behaviour
```py
Python 3.6.5 (default, Jun 17 2018, 12:26:58)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateparser
>>> dateparser.__version__
'0.6.0'
>>> dateparser.parse('7 days from now')
datetime.datetime(2019, 2, 19, 17, 6, 11, 572247)
>>> dateparser.parse('in 7 days')
datetime.datetime(2019, 2, 19, 17, 6, 14, 819151)
```

0.7 shows failed behavior
```python
Python 3.6.5 (default, Jun 17 2018, 12:26:58)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateparser
>>> dateparser.__version__
'0.7.1'
>>> dateparser.parse('7 days from now')
>>> dateparser.parse('in 7 days')
datetime.datetime(2019, 2, 19, 17, 8, 39, 230225)
```

### PR DESCRIPTION
**Pull request by harsh9200**
fixes #502 

### Before:
```
>>> dateparser.parse("now")
datetime.datetime(2020, 3, 23, 0, 32, 3, 521286)

>>> dateparser.parse("10 days from now")

```

### After:
```
>>> dateparser.parse("now")
datetime.datetime(2020, 3, 23, 0, 32, 3, 521286)

>>> dateparser.parse("10 days from now")
datetime.datetime(2020, 4, 2, 0, 32, 11, 25878)
```

### CODE REVIEW

**Comment by harsh9200** [comment]
Any particular reason why this is failing?

**Comment by Gallaecio** [comment]
Don’t mind the project coverage test. [The tests pass](https://travis-ci.org/github/scrapinghub/dateparser/pull_requests) and you have covered your changes with tests.

**Comment by harsh9200** [comment]
I am getting this Error @Gallaecio 

```
C:\Users\hagar\dateparser>python scripts/write_complete_data.py
Traceback (most recent call last):
  File "scripts/write_complete_data.py", line 115, in <module>
  File "scripts/write_complete_data.py", line 79, in main
  File "scripts/write_complete_data.py", line 58, in _get_complete_date_translation_data
  File "E:\Softwares\Python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "E:\Softwares\Python\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 80: character maps to <undefined>
```

**Comment by harsh9200** [comment]
I changed the following wherever the error occurred in scripts/write_complete_data.py

```
with open(cldr_date_directory + language + '.json') as f:
with open(cldr_date_directory + language + '.json', 'rb') as f:`
```

Is this the right way?

**Comment by Gallaecio** [comment]
> Is this the right way?

In cases where the read data goes into `json.loads`, I think that change is correct.

**Pull request closed without merging**
