### PR TITLE
added support for decade on hindi language

### PR DESCRIPTION
**Pull request by Mr-Sunglasses**
Added support for decade on hindi langauage

### CODE REVIEW

**Review by Gallaecio — APPROVED** [review]

**Comment by Mr-Sunglasses** [comment]
@Gallaecio I can't abel to fix this error `AssertionError: The content of the file "../dateparser/data/date_translation_data/hi.py" doesn't match the content of the generated file.`

**Comment by Mr-Sunglasses** [comment]
Screenshot 2021-09-26 at 2 37 25 AM
Screenshot 2021-09-26 at 2 37 40 AM

**Comment by Mr-Sunglasses** [comment]
### @Gallaecio 
**_After following these Instructions_*

Screenshot 2021-09-26 at 2 40 24 AM
*


**_It is giving this error_**

Screenshot 2021-09-26 at 2 41 01 AM

**Comment by Gallaecio** [comment]
You are running `python3 write_script_data.py`, but I think you are meant to be running `python3 dateparser_scripts/write_script_data.py` from the parent folder instead. Ideally that should not be needed, but I imagine that is how things work at the moment.

**Comment by Mr-Sunglasses** [comment]
@Gallaecio The problem - E               ### **_AssertionError: The content of the file "../dateparser/data/date_translation_data/hi.py" doesn't match the content of the generated file._**

Occurs when i edit the file ../dateparser/data/date_translation_data/hi.py , All the tests are successful ### **_decade_** in hindi is working fine but this error in test is not fixing.

**Comment by Gallaecio** [comment]
Are you editing `hi.py` manually?

**Comment by Mr-Sunglasses** [comment]
Yes I'm editing it manually

**Comment by Gallaecio** [comment]
You are supposed to edit the YAML file and let `python3 dateparser_scripts/write_script_data.py` update the other files. That file is not meant to be edited manually.

**Comment by Mr-Sunglasses** [comment]
@Gallaecio Thanks I am creating a new pr with all these changes

**Pull request closed without merging**
